import json

with open('sample.ipynb', 'r', encoding='utf-8') as f:
    nb = json.load(f)

# CELL 0: title
nb['cells'][0]['source'] = ['# Student Stress Classification\n\nMachine Learning Assignment - Part E\n\nDataset: Student Stress Survey (843 college students, ages 18-21)']

# CELL 2: EDA
cell2 = (
    'df = pd.read_csv("Stress_Dataset.csv")\n'
    '\n'
    'col_rename = {\n'
    '    "Gender": "gender",\n'
    '    "Age": "age",\n'
    '    "Have you recently experienced stress in your life?": "stress_experienced",\n'
    '    "Have you noticed a rapid heartbeat or palpitations?": "heart_palpitations",\n'
    '    "Have you been dealing with anxiety or tension recently?": "anxiety",\n'
    '    "Do you face any sleep problems or difficulties falling asleep?": "sleep_problems",\n'
    '    "Have you been dealing with anxiety or tension recently?.1": "anxiety_dup",\n'
    '    "Have you been getting headaches more often than usual?": "headaches",\n'
    '    "Do you get irritated easily?": "irritability",\n'
    '    "Do you have trouble concentrating on your academic tasks?": "concentration_issues",\n'
    '    "Have you been feeling sadness or low mood?": "sadness",\n'
    '    "Have you been experiencing any illness or health issues?": "illness",\n'
    '    "Do you often feel lonely or isolated?": "loneliness",\n'
    '    "Do you feel overwhelmed with your academic workload?": "academic_overload",\n'
    '    "Are you in competition with your peers, and does it affect you?": "peer_competition",\n'
    '    "Do you find that your relationship often causes you stress?": "relationship_stress",\n'
    '    "Are you facing any difficulties with your professors or instructors?": "professor_difficulties",\n'
    '    "Is your working environment unpleasant or stressful?": "work_stress",\n'
    '    "Do you struggle to find time for relaxation and leisure activities?": "leisure_lack",\n'
    '    "Is your hostel or home environment causing you difficulties?": "home_difficulties",\n'
    '    "Do you lack confidence in your academic performance?": "academic_confidence_lack",\n'
    '    "Do you lack confidence in your choice of academic subjects?": "subject_confidence_lack",\n'
    '    "Academic and extracurricular activities conflicting for you?": "activity_conflict",\n'
    '    "Do you attend classes regularly?": "class_attendance",\n'
    '    "Have you gained/lost weight?": "weight_change",\n'
    '    "Which type of stress do you primarily experience?": "stress_type",\n'
    '}\n'
    'df.rename(columns=col_rename, inplace=True)\n'
    'df.drop(columns=["anxiety_dup"], inplace=True)\n'
    '\n'
    '# Simplify target labels\n'
    'df["stress_type"] = df["stress_type"].str.extract(r"^(\\w+)")\n'
    '\n'
    '# Basic info\n'
    'print(df.shape)\n'
    'print(df.head(7))\n'
    'print(df.info())\n'
    'print(df.describe().T)\n'
    '\n'
    '# Missing & duplicates\n'
    'print("Missing:", df.isnull().sum().sum())\n'
    'print("Duplicates:", df.duplicated().sum())\n'
    'df.drop_duplicates(inplace=True)\n'
    'print("After removing duplicates:", df.shape)\n'
    '\n'
    '# Encode target\n'
    'df["stress_type"] = LabelEncoder().fit_transform(df["stress_type"])\n'
    '# 0=Distress, 1=Eustress, 2=No\n'
    '\n'
    '# Class balance\n'
    'print(df["stress_type"].value_counts())\n'
    'df["stress_type"].value_counts().plot(kind="bar")\n'
    'plt.title("Stress Type Distribution")\n'
    'plt.xlabel("Stress Type (0=Distress, 1=Eustress, 2=No Stress)")\n'
    'plt.tight_layout()\n'
    'plt.show()\n'
    '\n'
    '# Histograms\n'
    'df.hist(figsize=(18, 14), bins=10)\n'
    'plt.tight_layout()\n'
    'plt.show()\n'
    '\n'
    '# Boxplots\n'
    'df.plot(kind="box", subplots=True, layout=(5, 5), figsize=(18, 16))\n'
    'plt.tight_layout()\n'
    'plt.show()\n'
    '\n'
    '# Correlation heatmap\n'
    'plt.figure(figsize=(14, 12))\n'
    'sns.heatmap(df.corr(numeric_only=True), annot=True, fmt=".1f", cmap="coolwarm", square=True, annot_kws={"size": 6})\n'
    'plt.title("Correlation Matrix")\n'
    'plt.tight_layout()\n'
    'plt.show()\n'
    '\n'
    '# Pairplot\n'
    'sns.pairplot(df[["anxiety", "academic_overload", "sadness", "sleep_problems", "stress_type"]], hue="stress_type")\n'
    'plt.show()\n'
    '\n'
    '# Statistics\n'
    'num_cols = df.select_dtypes(include=np.number).columns\n'
    'stats = pd.DataFrame({\n'
    '    "mean": df[num_cols].mean(),\n'
    '    "mode": df[num_cols].mode().iloc[0],\n'
    '    "median": df[num_cols].median(),\n'
    '    "std": df[num_cols].std(),\n'
    '    "Q1": df[num_cols].quantile(0.25),\n'
    '    "Q3": df[num_cols].quantile(0.75)\n'
    '})\n'
    'print(stats)\n'
    '\n'
    '# Drop correlated feature\n'
    'df.drop(columns=["subject_confidence_lack"], inplace=True)\n'
    'df.to_csv("Stress_Dataset_cleaned.csv", index=False)\n'
    'print("Done. Saved Stress_Dataset_cleaned.csv")\n'
)
nb['cells'][2]['source'] = [cell2]

# CELL 3: Supervised
cell3 = (
    'df = pd.read_csv("Stress_Dataset_cleaned.csv")\n'
    'X = df.drop(columns=["stress_type"])\n'
    'y = df["stress_type"]\n'
    'X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)\n'
    '\n'
    'total = len(y)\n'
    'print(f"Total: {total} | Training: {X_train.shape[0]} ({X_train.shape[0]/total*100:.1f}%) | Test: {X_test.shape[0]} ({X_test.shape[0]/total*100:.1f}%)")\n'
    'print("\\nTrain class counts and %:")\n'
    'for cls, cnt in y_train.value_counts().items():\n'
    '    print(f"  Class {cls}: {cnt} ({cnt/len(y_train)*100:.1f}%)")\n'
    'print("\\nTest class counts and %:")\n'
    'for cls, cnt in y_test.value_counts().items():\n'
    '    print(f"  Class {cls}: {cnt} ({cnt/len(y_test)*100:.1f}%)")\n'
    '\n'
    '# === Random Forest (3 experiments) ===\n'
    'print("\\n=== RANDOM FOREST ===")\n'
    'rf_configs = [\n'
    '    {"n_estimators": 50, "max_depth": 5},\n'
    '    {"n_estimators": 100, "max_depth": 10},\n'
    '    {"n_estimators": 200, "max_depth": None},\n'
    ']\n'
    'for i, params in enumerate(rf_configs, 1):\n'
    '    rf = RandomForestClassifier(**params, random_state=42, class_weight="balanced")\n'
    '    rf.fit(X_train, y_train)\n'
    '    train_acc = accuracy_score(y_train, rf.predict(X_train))\n'
    '    test_acc = accuracy_score(y_test, rf.predict(X_test))\n'
    '    print(f"\\nExperiment {i}: {params}")\n'
    '    print(f"  Train: {train_acc:.4f} | Test: {test_acc:.4f} | Overfit: {\'Yes\' if train_acc - test_acc > 0.05 else \'No\'}")\n'
    '    print(classification_report(y_test, rf.predict(X_test)))\n'
    '    ConfusionMatrixDisplay.from_estimator(rf, X_test, y_test)\n'
    '    plt.title(f"RF Experiment {i}")\n'
    '    plt.show()\n'
    '\n'
    '# === Decision Tree (3 experiments) ===\n'
    'print("\\n=== DECISION TREE ===")\n'
    'dt_configs = [\n'
    '    {"max_depth": 3},\n'
    '    {"max_depth": 5},\n'
    '    {"max_depth": 10},\n'
    ']\n'
    'for i, params in enumerate(dt_configs, 1):\n'
    '    dt = DecisionTreeClassifier(**params, random_state=42, class_weight="balanced")\n'
    '    dt.fit(X_train, y_train)\n'
    '    train_acc = accuracy_score(y_train, dt.predict(X_train))\n'
    '    test_acc = accuracy_score(y_test, dt.predict(X_test))\n'
    '    print(f"\\nExperiment {i}: {params}")\n'
    '    print(f"  Train: {train_acc:.4f} | Test: {test_acc:.4f} | Overfit: {\'Yes\' if train_acc - test_acc > 0.05 else \'No\'}")\n'
    '    print(classification_report(y_test, rf.predict(X_test)))\n'
    '    ConfusionMatrixDisplay.from_estimator(dt, X_test, y_test)\n'
    '    plt.title(f"DT Experiment {i}")\n'
    '    plt.show()\n'
    '\n'
    '# Decision Boundary\n'
    'X_train_2d = X_train[["anxiety", "academic_overload"]]\n'
    'X_test_2d = X_test[["anxiety", "academic_overload"]]\n'
    'dt2 = DecisionTreeClassifier(max_depth=5, random_state=42, class_weight="balanced")\n'
    'dt2.fit(X_train_2d, y_train)\n'
    'fig, ax = plt.subplots(figsize=(10, 6))\n'
    'DecisionBoundaryDisplay.from_estimator(dt2, X_test_2d, ax=ax, cmap="coolwarm", alpha=0.5)\n'
    'ax.scatter(X_test_2d["anxiety"], X_test_2d["academic_overload"], c=y_test, cmap="coolwarm", edgecolors="k", s=20)\n'
    'ax.set_xlabel("Anxiety")\n'
    'ax.set_ylabel("Academic Overload")\n'
    'ax.set_title("Decision Tree - Decision Boundary")\n'
    'plt.show()\n'
)
nb['cells'][3]['source'] = [cell3]

# CELL 4: Unsupervised
cell4 = (
    'df = pd.read_csv("Stress_Dataset_cleaned.csv")\n'
    'X_raw = df.drop(columns=["stress_type"])\n'
    '\n'
    '# Scale features (required for distance-based algorithms)\n'
    'scaler = MinMaxScaler()\n'
    'X = pd.DataFrame(scaler.fit_transform(X_raw), columns=X_raw.columns)\n'
    '\n'
    '# === K-Means (5 different k values) ===\n'
    'print("=== K-MEANS ===")\n'
    'k_values = [2, 3, 4, 5, 6]\n'
    'silhouette_scores = []\n'
    '\n'
    'for k in k_values:\n'
    '    kmeans = KMeans(n_clusters=k, init="k-means++", random_state=42)\n'
    '    labels = kmeans.fit_predict(X)\n'
    '    score = silhouette_score(X, labels)\n'
    '    silhouette_scores.append(score)\n'
    '    print(f"k={k} | Silhouette Score: {score:.4f}")\n'
    '\n'
    'plt.figure(figsize=(8, 5))\n'
    'plt.plot(k_values, silhouette_scores, marker="o")\n'
    'plt.xlabel("Number of Clusters (k)")\n'
    'plt.ylabel("Silhouette Score")\n'
    'plt.title("K-Means - Silhouette Score per k")\n'
    'plt.tight_layout()\n'
    'plt.show()\n'
    '\n'
    'best_k = k_values[np.argmax(silhouette_scores)]\n'
    'print(f"\\nBest k: {best_k} (score: {max(silhouette_scores):.4f})")\n'
    '\n'
    'kmeans_best = KMeans(n_clusters=best_k, init="k-means++", random_state=42)\n'
    'labels_best = kmeans_best.fit_predict(X)\n'
    'plt.figure(figsize=(8, 5))\n'
    'plt.scatter(X["anxiety"], X["academic_overload"], c=labels_best, cmap="rainbow", s=20)\n'
    'plt.xlabel("Anxiety (scaled)")\n'
    'plt.ylabel("Academic Overload (scaled)")\n'
    'plt.title(f"K-Means Clustering (k={best_k})")\n'
    'plt.tight_layout()\n'
    'plt.show()\n'
    '\n'
    '# === Hierarchical Clustering (3 experiments) ===\n'
    'print("\\n=== HIERARCHICAL CLUSTERING ===")\n'
    '\n'
    'plt.figure(figsize=(14, 8))\n'
    'plt.title("Dendrogram (truncated)")\n'
    'plt.xlabel("Data Points")\n'
    'plt.ylabel("Euclidean Distance")\n'
    'shc.dendrogram(shc.linkage(X, method="ward"), truncate_mode="level", p=5)\n'
    'plt.tight_layout()\n'
    'plt.show()\n'
    '\n'
    'hc_configs = [\n'
    '    {"n_clusters": 2, "linkage": "ward"},\n'
    '    {"n_clusters": 3, "linkage": "ward"},\n'
    '    {"n_clusters": 3, "linkage": "complete"},\n'
    ']\n'
    'for i, params in enumerate(hc_configs, 1):\n'
    '    hc = AgglomerativeClustering(**params)\n'
    '    labels = hc.fit_predict(X)\n'
    '    score = silhouette_score(X, labels)\n'
    '    print(f"\\nExperiment {i}: {params}")\n'
    '    print(f"  Silhouette Score: {score:.4f}")\n'
    '    plt.figure(figsize=(8, 5))\n'
    '    plt.scatter(X["anxiety"], X["academic_overload"], c=labels, cmap="rainbow", s=20)\n'
    '    plt.xlabel("Anxiety (scaled)")\n'
    '    plt.ylabel("Academic Overload (scaled)")\n'
    '    plt.title(f"Hierarchical Experiment {i}: {params}")\n'
    '    plt.tight_layout()\n'
    '    plt.show()\n'
)
nb['cells'][4]['source'] = [cell4]

with open('sample.ipynb', 'w', encoding='utf-8') as f:
    json.dump(nb, f, indent=1)


print('All cells updated successfully.')
